name: Translate Issues

on:
  issue_comment:
    types: [created]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Translate issue
        uses: usthe/issues-translate-action@v2.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
