name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Translate Issues
        uses: usthe/issues-translate-action@v2.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
