name: Unknown Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Translate Issues
      uses: usthe/issues-translate-action@v2.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
